### 예외 처리

- 예외 처리 기본 : try, throw, catch 문을 중심으로 예외 처리를 구성하는 방법
- 스택 풀기 : 스택 메모리에 불필요한 데이터가 쌓이지 않게 하려는 예외 처리 구조
- 메모리 예외 처리 : 객체가 생성 혹은 소멸하는 과정에서 발생하는 예외를 다루는 방법



#### 10.1.1 기본 활용 방법

```c++
try
{
    ...//작업1.
    if(error 발생)
        throw errorcode;
    ...//작업2.
    if(error 발생)
        throw errorcode; 
}
catch(int nExp)
{
    
}
//throw문은 return문 처럼 오류 코드 값을 기술할 수 있다. 그러면 catch문 블록에서 마치 함수의 매개변수처럼 값을 받을 수 있다.
```

```c++
#include <iostream>
using namespace std;

int main()
{
	int a = 100, b;
	cout << "Input number: ";
	cin >> b;

	try
	{
		//예외 검사 후 '던진다.'
		if (b == 0)
			throw b;

		else
			cout << a / b << endl;
	}
	catch (int nExp) // nExp : b가 대입됨
	{
		cout << "Error: " << nExp << "으로 나눌 수 없다." << endl;
	}
}
```

- 만일 예외 처리할 경우가 여러 가지라면 catch문 블록 내부에서 다시 switch-case문이나 다중 if문을 이용.
- catch문 블록을 다중화 하거나



#### 10.1.2 catch 다중화

- catch문은 여러 개로 구현할 수 있는데 throw문으로 예외를 던질 때 값의 자료형이 int인 경우와 char인 경우를 각각 다른 catch문으로 만들 수 있다.

```c++
// int와 char 자료형의 catch 다중화, 함수가 throw하면 main문에서 catch함.
#include <iostream>
using namespace std;

void ExceptTest1()
{
	int nInput;
	cout << "1~10 양의 정수를 입력하세요.: ";
	cin >> nInput;

	// 범위를 벗어난 숫자면 예외를 던진다.
	if (nInput < 1 || nInput > 10)
		throw nInput;
}

void ExceptTest2()
{
	char ch;
	cout << "Menu: [A]dd\t[D]elete\t[E]xit\n";
	cin >> ch;

	//없는 메뉴를 선택하면 예외를 던진다.
	if (ch != 'A' && ch != 'D' && ch != 'E')
		throw ch;
}

int main()
{
	cout << "Begin" << endl;
	try
	{
		// 정상적인 흐름이 한 블록 안에 모두 보인다.
		ExceptTest1();
		ExceptTest2();
	}
	catch (int nExp)
	{
		cout << "Error:" << nExp << "은 범위를 벗어난 숫자입니다." << endl;
	}
	catch (char ch)
	{
		cout << "Error:" << ch << "알 수 없는 메뉴입니다." << endl;
	}

	cout << "End" << endl;

	return 0;
}
```

- catch(...)문 블록 내부에서 다시 예외 던지는 것도 가능

```c++
try{
    
}
catch(...) {
    try{
        
    }
    catch(...)
    {
        
    }
}
```



#### 10.1.3 예외클래스

catch('형식') - '형식'에 사용자 정의 클래스도 포함된다. 즉 catch(CMyException &exp)같은 코드를 사용할 수 있다.

```c++
// 예외 클래스 사용
#include <iostream>
using namespace std;

class CMyException
{
public:
    //예외 코드와 메시지를 입력받는다.
    CMyException(int nCode, const char* pszMsg)
    {
        m_nErrorCode = nCode;
        strcpy_s(m_szMsg, sizeof(m_szMsg), pszMsg);
    }

    int GetErrorCode() const { return m_nErrorCode; }
    const char* GetMessage() const { return m_szMsg; }

private:
    int m_nErrorCode;
    char m_szMsg[128];
};

int main()
{
    try 
    {
        int nInput = 0;
        cout << "양의 정수를 입력하세요: ";
        cin >> nInput;

        if (nInput < 0)
        {
            CMyException exp(10, "양의 정수를 입력해야 합니다.");
            throw exp;
        }
    }

    catch (CMyException &exp)
    {
        cout << "ERROR CODE [" << exp.GetErrorCode() << "]"
            << exp.GetMessage() << endl;
    }
}
```



### 10.2 스택 풀기(Stack unwinding)

- p430



#### 10.3 메모리 예외 처리

- 너무 큰 메모리를 할당하려고 하면 오류가 발생한다. 이때 메모리를 할당해주는 함수나 연산자는 NULL을 반환한다. 그래서 보통 반환값이 NULL인지 비교하는 방식으로 메모리 할당에 관한 예외 처리를 시도한다. 하지만 구조화된 예외 처리를 이용하면 더 좋다.

```C++
// 구조화된 메모리 예외 처리
#include <new> // bad_alloc 클래스를 사용하기 위한 헤더
#include <iostream>
using namespace std;

class CTest
{
public:
	CTest(int nSize)
	{
		//메모리 할당에 실패하면 예외를 던진다.
		m_pszData = new char[nSize];
	}
	~CTest()
	{
		delete[] m_pszData;
		cout << "정상적으로 객체가 소멸함." << endl;
 	}

private:
	char* m_pszData;
};

int main()
{
	try
	{
		int nSize;
		cout << "Input size";
		//사용자가 입력한 값을 검증 없이 그대로 사용해 객체를 생성
		cin >> nSize;
		CTest a(nSize);
	}
	catch (bad_alloc& exp)// 메모리 생성 실패 오류 잡아냄.
	{
		// 시스템이 밝힌 원인을 출력한다.
		cout << exp.what() << endl; //출력되는 메시지는 운영체제가 알려주는 것.
		cout << "Error: CTest()" << endl;
	}
}
/*
Input size100
정상적으로 객체가 소멸함.
*/

/*
Input size-1
bad array new length
Error: CTest()
*/
```

